version: '3'

services:
  app:
    container_name: fms-logviewer-backend
    restart: unless-stopped
    build: .
    ports:
      - '${PORT}:${PORT}'
    environment:
      PORT: '${PORT}'
      TZ: 'Europe/Berlin'
    volumes:
      - ${LOGFILES_ROOT_PATH_LINUX}:${LOGFILES_ROOT_PATH_LINUX}